# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scp


class _Aiml(_Scp):
    _type = "aiml"
    _icon_dir = "resources/scp/aiml"


class Aicr(_Aiml):
    _icon = "AICR.png"


class Aimlopsplatform(_Aiml):
    _icon = "AIMLOpsPlatform.png"


class Cloudmlexperiments(_Aiml):
    _icon = "CloudMLExperiments.png"


class Cloudmlnotebook(_Aiml):
    _icon = "CloudMLNotebook.png"


class Cloudmlpipeline(_Aiml):
    _icon = "CloudMLPipeline.png"


class Cloudmlstudio(_Aiml):
    _icon = "CloudMLStudio.png"


class Textapi(_Aiml):
    _icon = "TextAPI.png"


# Aliases
