# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scp


class _Compute(_Scp):
    _type = "compute"
    _icon_dir = "resources/scp/compute"


class Baremetalserver(_Compute):
    _icon = "BareMetalServer.png"


class Cloudfunctions(_Compute):
    _icon = "CloudFunctions.png"


class Gpuserver(_Compute):
    _icon = "GPUServer.png"


class Hpcbm(_Compute):
    _icon = "HPCBM.png"


class Hpccluster(_Compute):
    _icon = "HPCCluster.png"


class Multinodegpucluster(_Compute):
    _icon = "MultinodeGPUCluster.png"


class Vmautoscaling(_Compute):
    _icon = "VMAutoScaling.png"


class Virtualdesktop(_Compute):
    _icon = "VirtualDesktop.png"


class Virtualserver(_Compute):
    _icon = "VirtualServer.png"


class Virtualserverdr(_Compute):
    _icon = "VirtualServerDR.png"


# Aliases
