# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scp


class _Container(_Scp):
    _type = "container"
    _icon_dir = "resources/scp/container"


class Containerregistry(_Container):
    _icon = "ContainerRegistry.png"


class Kubernetesapps(_Container):
    _icon = "KubernetesApps.png"


class Kubernetesengine(_Container):
    _icon = "KubernetesEngine.png"


# Aliases
