# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scp


class _Dataanalytics(_Scp):
    _type = "dataanalytics"
    _icon_dir = "resources/scp/dataanalytics"


class Apachekafka(_Dataanalytics):
    _icon = "ApacheKafka.png"


class Cloudhadoop(_Dataanalytics):
    _icon = "CloudHadoop.png"


class Datacatalog(_Dataanalytics):
    _icon = "DataCatalog.png"


class Dataflow(_Dataanalytics):
    _icon = "DataFlow.png"


class Dataops(_Dataanalytics):
    _icon = "DataOps.png"


class Datawrangler(_Dataanalytics):
    _icon = "DataWrangler.png"


class Elasticsearch(_Dataanalytics):
    _icon = "Elasticsearch.png"


class Quickquery(_Dataanalytics):
    _icon = "QuickQuery.png"


class Sqream(_Dataanalytics):
    _icon = "SQream.png"


class Vmwaregreenplum(_Dataanalytics):
    _icon = "VMwareGreenplum.png"


class Vertica(_Dataanalytics):
    _icon = "Vertica.png"


# Aliases
