# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scp


class _Database(_Scp):
    _type = "database"
    _icon_dir = "resources/scp/database"


class Cassandra(_Database):
    _icon = "Cassandra.png"


class Cubrid(_Database):
    _icon = "Cubrid.png"


class Epas(_Database):
    _icon = "EPAS.png"


class Mariadb(_Database):
    _icon = "MariaDB.png"


class Microsoftsqlserver(_Database):
    _icon = "MicrosoftSQLServer.png"


class Mysql(_Database):
    _icon = "MySQL.png"


class Postgresql(_Database):
    _icon = "PostgreSQL.png"


class Redis(_Database):
    _icon = "Redis.png"


class Tibero(_Database):
    _icon = "Tibero.png"


# Aliases
