# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scp


class _Devopstools(_Scp):
    _type = "devopstools"
    _icon_dir = "resources/scp/devopstools"


class Devopscode(_Devopstools):
    _icon = "DevOpsCode.png"


class Devopsservice(_Devopstools):
    _icon = "DevOpsService.png"


class Githubenterprise(_Devopstools):
    _icon = "GitHubEnterprise.png"


# Aliases
