# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scp


class _Hybridcloud(_Scp):
    _type = "hybridcloud"
    _icon_dir = "resources/scp/hybridcloud"


class Edgeserver(_Hybridcloud):
    _icon = "EdgeServer.png"


# Aliases
