# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scp


class _Management(_Scp):
    _type = "management"
    _icon_dir = "resources/scp/management"


class Cloudmonitoring(_Management):
    _icon = "CloudMonitoring.png"


class Iam(_Management):
    _icon = "IAM.png"


class Loggingaudit(_Management):
    _icon = "LoggingAudit.png"


class Vmmigration(_Management):
    _icon = "VMMigration.png"


# Aliases
