# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scp


class _Networking(_Scp):
    _type = "networking"
    _icon_dir = "resources/scp/networking"


class Cloudlancampus(_Networking):
    _icon = "CloudLANCampus.png"


class Cloudlandatacenter(_Networking):
    _icon = "CloudLANDataCenter.png"


class Cloudwan(_Networking):
    _icon = "CloudWAN.png"


class Dns(_Networking):
    _icon = "DNS.png"


class Directconnect(_Networking):
    _icon = "DirectConnect.png"


class Firewall(_Networking):
    _icon = "Firewall.png"


class Gslb(_Networking):
    _icon = "GSLB.png"


class Globalcdn(_Networking):
    _icon = "GlobalCDN.png"


class Loadbalancer(_Networking):
    _icon = "LoadBalancer.png"


class Securitygroup(_Networking):
    _icon = "SecurityGroup.png"


class Transitgateway(_Networking):
    _icon = "TransitGateway.png"


class Vpc(_Networking):
    _icon = "VPC.png"


class Vpn(_Networking):
    _icon = "VPN.png"


# Aliases
