# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Scp


class _Security(_Scp):
    _type = "security"
    _icon_dir = "resources/scp/security"


class Certificatemanager(_Security):
    _icon = "CertificateManager.png"


class Ddosprotection(_Security):
    _icon = "DDoSProtection.png"


class Ips(_Security):
    _icon = "IPS.png"


class Keymanagementservice(_Security):
    _icon = "KeyManagementService.png"


class Secretvault(_Security):
    _icon = "SecretVault.png"


class Securedfirewall(_Security):
    _icon = "SecuredFirewall.png"


class Securedvpn(_Security):
    _icon = "SecuredVPN.png"


class Securitymonitoring(_Security):
    _icon = "SecurityMonitoring.png"


class Waf(_Security):
    _icon = "WAF.png"


# Aliases
